Add related syncing
cmberryau/entity_sync pull request #15
Opened 2021-04-21 00:56 UTC by anhphamduy

2021-04-22 01:42 UTC, cmberryau requested changes

2021-04-22 01:42 UTC, cmberryau commented on lib/src/endpoints.dart
> +    required String remoteKey,
remove One in signature here

2021-04-22 01:42 UTC, cmberryau commented on lib/src/endpoints.dart
> +  Future<EndpointResult<TSyncable>> pullOneByRemoteKey({
remove One in signature here

2021-05-06 06:19 UTC, anhphamduy commented
@cmberryau I've resolved all the requested changes. Gonna merge this in now.

2021-05-06 06:20 UTC, merged